jobs:
- job:
  displayName: ubuntu-latest
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - script: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH
  - script: conda create --yes --quiet --name goldstandard_CI
    displayName: Create Anaconda environment
  - script: |
      source activate goldstandard_CI
      conda install --yes -c conda-forge mamba python=3.9
      mamba install --yes -c conda-forge -c bioconda compilers meson gperftools sdsl-lite libdivsufsort libsequence zlib cmake
    displayName: Install dependencies
  - script: |
      git clone --recurse-submodules https://github.com/bcgsc/btllib
      cd btllib
      git checkout mi_bf_constructor2
      source activate goldstandard_CI
      ./compile
    displayName: Install btllib
  - script: |
      source activate goldstandard_CI
      export LDFLAGS="-L/home/vsts/work/1/s/btllib/install/lib $LDFLAGS"
      export CPPFLAGS="-isystem/home/vsts/work/1/s/btllib/install/include $CPPFLAGS"
      meson build --prefix=$(pwd)/test_build
      cd build
      ninja install
    displayName: Compile GoldStandard
