jobs:
  - job:
    displayName: ubuntu-latest
    pool:
      vmImage: "ubuntu-latest"

    steps:
      - script: |
          mkdir -p ~/miniforge3
          curl -L https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh  -o ~/miniforge3/miniforge.sh
          bash ~/miniforge3/miniforge.sh -b -u -p ~/miniforge3
          rm -rf  ~/miniforge3/miniforge.sh
          ~/miniforge3/bin/conda init bash
          ~/miniforge3/bin/conda init zsh
          export CONDA=$(realpath ~/miniforge3/bin)
          echo "##vso[task.prependpath]$CONDA"
        displayName: Install conda
      - script: conda create --yes --quiet --name aakomp_CI
        displayName: Create Anaconda environment
      - script: |
          source activate aakomp_CI
          conda install --yes -c conda-forge mamba python=3.9
          mamba install --yes -c conda-forge -c bioconda compilers meson gperftools sdsl-lite libdivsufsort libsequence zlib cmake btllib gperftools libsequence boost-cpp  r-base   r-ggplot2   r-dplyr   r-readr   r-cairo   r-gridextra r-pracma
        displayName: Install dependencies
      - script: |
          source activate aakomp_CI
          export BOOST_ROOT=$CONDA_PREFIX
          meson build --prefix=$(pwd)/test_build
          cd build
          ninja install
        displayName: Compile aaKomp
      - script: |
          sudo apt-get update
          sudo apt-get install -y aria2
          aria2c -x 4 -s 4 -d test https://zenodo.org/records/15421506/files/primates_odb12.tar.gz
        displayName: Download primates_odb12.tar.gz
      - script: |
          source activate aakomp_CI
          export BOOST_ROOT=$CONDA_PREFIX
          export PATH=$(pwd)/test_build/bin:$PATH
          cd test
          ./aakomp_test_demo.sh
        displayName: Test run for aaKomp

  - job:
    displayName: mac-latest
    pool:
      vmImage: 'macOS-latest'
    steps:
      - script: |
          mkdir -p ~/miniforge3
          curl -L https://github.com/conda-forge/miniforge/releases/download/25.3.0-2/Miniforge3-25.3.0-2-MacOSX-x86_64.sh  -o ~/miniforge3/miniforge.sh
          bash ~/miniforge3/miniforge.sh -b -u -p ~/miniforge3
          rm -rf  ~/miniforge3/miniforge.sh
          ~/miniforge3/bin/conda init bash
          ~/miniforge3/bin/conda init zsh
          export CONDA=$(realpath ~/miniforge3/bin)
          echo "##vso[task.prependpath]$CONDA"
        displayName: Install conda
      - script: conda create --yes --quiet --name aakomp_CI
        displayName: Create Anaconda environment
      - script: |
          source activate aakomp_CI
          conda install --yes -c conda-forge mamba python=3.9
          mamba install --yes -c conda-forge -c bioconda compilers meson gperftools sdsl-lite libdivsufsort libsequence zlib cmake btllib gperftools libsequence numpy matplotlib boost-cpp r-base   r-ggplot2   r-dplyr   r-readr   r-cairo   r-gridextra r-pracma
        displayName: Install dependencies
      - script: |
          source activate aakomp_CI
          export BOOST_ROOT=$CONDA_PREFIX
          meson build --prefix=$(pwd)/test_build
          cd build
          ninja install
        displayName: Compile aaKomp
      - script: |
          sudo apt-get update
          sudo apt-get install -y aria2
          aria2c -x 4 -s 4 -d test https://zenodo.org/records/15421506/files/primates_odb12.tar.gz
        displayName: Download primates_odb12.tar.gz
      - script: |
          source activate aakomp_CI
          export BOOST_ROOT=$CONDA_PREFIX
          export PATH=$(pwd)/test_build/bin:$PATH
          cd test
          ./aakomp_test_demo.sh
        displayName: Test run for aaKomp

