jobs:
  - job:
    displayName: ubuntu-latest
    pool:
      vmImage: "ubuntu-latest"

    steps:
      - script: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: Add conda to PATH
      - script: conda create --yes --quiet --name aakomp_CI
        displayName: Create Anaconda environment
      - script: |
          source activate aakomp_CI
          conda install --yes -c conda-forge mamba python=3.9
          mamba install --yes -c conda-forge -c bioconda compilers meson gperftools sdsl-lite libdivsufsort libsequence zlib cmake btllib gperftools libsequence numpy matplotlib
        displayName: Install dependencies
      - script: |
          source activate aakomp_CI
          meson build --prefix=$(pwd)/test_build
          cd build
          ninja install
        displayName: Compile aaKomp
